### ISSUE TITLE
python compatability

### ISSUE THREAD

**Issue by hamanjam** [CyberRad/CoopSolar#1]
Trying to run directly, I am getting errors with both python and python3:

 python3 getcharge.py 
  File "/home/pi/usb-485/CoopSolar/getcharge.py", line 30
    print "Solar Voltage", solarVoltage
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Solar Voltage", solarVoltage)?

Is there something I'm missing or a set of prereqs I'm missing?

**Comment by CyberRad** [comment]
It looks like there were some changes with pymodbus that has caused some issues. I was able to get around this by adding the parentheses in the print statement and ensuring that I have pymodbus and influxdb installed for python3. Once those were met I was able to run using python3. I will look into updating the code and the readme when I can.

**Comment by CyberRad** [comment]
New version of getcharge.py has been uploaded.
